// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// .\be\be_codegen.cpp:396

#ifndef _TAO_IDL_DDSPERFTESTS_H_
#define _TAO_IDL_DDSPERFTESTS_H_

#include /**/ "ace/pre.h"

#include "DDSPerfTestC.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// w:\ace_wrappers\tao\tao_idl\be\be_visitor_module/module_sh.cpp:49

namespace POA_DDSPerfTest
{
  

// TAO_IDL - Generated from
// w:\ace_wrappers\tao\tao_idl\be\be_visitor_module/module_sh.cpp:80

} // module DDSPerfTest

// TAO_IDL - Generated from 
// .\be\be_codegen.cpp:1157



TAO_END_VERSIONED_NAMESPACE_DECL


#if defined (__ACE_INLINE__)
#include "DDSPerfTestS.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"
#endif /* ifndef */

