// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:164

#ifndef _TAO_IDL_PUBMESSAGETYPESUPPORTC_H_
#define _TAO_IDL_PUBMESSAGETYPESUPPORTC_H_

#include /**/ "ace/pre.h"


#include "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Environment.h"
#include "dds/DCPS/Serializer.h"
#include "tao/Object.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Versioned_Namespace.h"

#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsDataWriterRemoteC.h"
#include "dds/DdsDcpsDataReaderRemoteC.h"
#include "dds/DdsDcpsTypeSupportTaoC.h"
#include "DDSPerfTestC.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// be/be_visitor_root/root_ch.cpp:62

namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}

// TAO_IDL - Generated from
// be/be_visitor_sequence/sequence_ch.cpp:101

#if !defined (_PUBMESSAGESEQ_CH_)
#define _PUBMESSAGESEQ_CH_

class PubMessageSeq;

typedef
  TAO_VarSeq_Var_T<
      PubMessageSeq,
      DDSPerfTest::PubMessage
    >
  PubMessageSeq_var;

typedef
  TAO_Seq_Out_T<
      PubMessageSeq,
      PubMessageSeq_var,
      DDSPerfTest::PubMessage
    >
  PubMessageSeq_out;

class  PubMessageSeq
  : public
      TAO_Unbounded_Sequence<
          DDSPerfTest::PubMessage
        >
{
public:
  PubMessageSeq (void);
  PubMessageSeq ( ::CORBA::ULong max);
  PubMessageSeq (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      DDSPerfTest::PubMessage* buffer, 
      ::CORBA::Boolean release = 0
    );
  PubMessageSeq (const PubMessageSeq &);
  ~PubMessageSeq (void);
  
  typedef PubMessageSeq_var _var_type;
};

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_interface.cpp:646

#if !defined (_PUBMESSAGETYPESUPPORT__VAR_OUT_CH_)
#define _PUBMESSAGETYPESUPPORT__VAR_OUT_CH_

class PubMessageTypeSupport;
typedef PubMessageTypeSupport *PubMessageTypeSupport_ptr;

typedef
  TAO_Objref_Var_T<
      PubMessageTypeSupport
    >
  PubMessageTypeSupport_var;

typedef
  TAO_Objref_Out_T<
      PubMessageTypeSupport
    >
  PubMessageTypeSupport_out;

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ch.cpp:54

#if !defined (_PUBMESSAGETYPESUPPORT_CH_)
#define _PUBMESSAGETYPESUPPORT_CH_

class  PubMessageTypeSupport
  : public virtual ::TAO::DCPS::TypeSupport
{
public:
  friend class TAO::Narrow_Utils<PubMessageTypeSupport>;
  typedef PubMessageTypeSupport_ptr _ptr_type;
  typedef PubMessageTypeSupport_var _var_type;
  
  // The static operations.
  static PubMessageTypeSupport_ptr _duplicate (PubMessageTypeSupport_ptr obj);
  
  static void _tao_release (PubMessageTypeSupport_ptr obj);
  
  static PubMessageTypeSupport_ptr _narrow (
      ::CORBA::Object_ptr obj
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  static PubMessageTypeSupport_ptr _unchecked_narrow (
      ::CORBA::Object_ptr obj
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  static PubMessageTypeSupport_ptr _nil (void)
  {
    return static_cast<PubMessageTypeSupport_ptr> (0);
  }
  
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t register_type (
      ::DDS::DomainParticipant_ptr participant,
      const char * type_name
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:210
  
  virtual ::CORBA::Boolean _is_a (
      const char *type_id
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  virtual const char* _interface_repository_id (void) const;
  virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
private:
  TAO::Collocation_Proxy_Broker *the_TAO_PubMessageTypeSupport_Proxy_Broker_;

protected:
  // Concrete interface only.
  PubMessageTypeSupport (void);
  
  // These methods travese the inheritance tree and set the
  // parents piece of the given class in the right mode.
  virtual void PubMessageTypeSupport_setup_collocation (void);
  
  // Concrete non-local interface only.
  PubMessageTypeSupport (
      IOP::IOR *ior,
      TAO_ORB_Core *orb_core = 0
    );
  
  // Non-local interface only.
  PubMessageTypeSupport (
      TAO_Stub *objref,
      ::CORBA::Boolean _tao_collocated = 0,
      TAO_Abstract_ServantBase *servant = 0,
      TAO_ORB_Core *orb_core = 0
    );
  
  virtual ~PubMessageTypeSupport (void);

private:
  // Private and unimplemented for concrete interfaces.
  PubMessageTypeSupport (const PubMessageTypeSupport &);
  
  void operator= (const PubMessageTypeSupport &);
};

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_interface.cpp:646

#if !defined (_PUBMESSAGEDATAWRITER__VAR_OUT_CH_)
#define _PUBMESSAGEDATAWRITER__VAR_OUT_CH_

class PubMessageDataWriter;
typedef PubMessageDataWriter *PubMessageDataWriter_ptr;

typedef
  TAO_Objref_Var_T<
      PubMessageDataWriter
    >
  PubMessageDataWriter_var;

typedef
  TAO_Objref_Out_T<
      PubMessageDataWriter
    >
  PubMessageDataWriter_out;

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ch.cpp:54

#if !defined (_PUBMESSAGEDATAWRITER_CH_)
#define _PUBMESSAGEDATAWRITER_CH_

class  PubMessageDataWriter
  : public virtual ::TAO::DCPS::DataWriterRemote
{
public:
  friend class TAO::Narrow_Utils<PubMessageDataWriter>;
  typedef PubMessageDataWriter_ptr _ptr_type;
  typedef PubMessageDataWriter_var _var_type;
  
  // The static operations.
  static PubMessageDataWriter_ptr _duplicate (PubMessageDataWriter_ptr obj);
  
  static void _tao_release (PubMessageDataWriter_ptr obj);
  
  static PubMessageDataWriter_ptr _narrow (
      ::CORBA::Object_ptr obj
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  static PubMessageDataWriter_ptr _unchecked_narrow (
      ::CORBA::Object_ptr obj
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  static PubMessageDataWriter_ptr _nil (void)
  {
    return static_cast<PubMessageDataWriter_ptr> (0);
  }
  
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::InstanceHandle_t _cxx_register (
      const ::DDSPerfTest::PubMessage & instance_data
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::InstanceHandle_t register_w_timestamp (
      const ::DDSPerfTest::PubMessage & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t unregister (
      const ::DDSPerfTest::PubMessage & instance_data,
      ::DDS::InstanceHandle_t handle
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t unregister_w_timestamp (
      const ::DDSPerfTest::PubMessage & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t write (
      const ::DDSPerfTest::PubMessage & instance_data,
      ::DDS::InstanceHandle_t handle
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDSPerfTest::PubMessage & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t dispose (
      const ::DDSPerfTest::PubMessage & instance_data,
      ::DDS::InstanceHandle_t instance_handle
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDSPerfTest::PubMessage & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSPerfTest::PubMessage & key_holder,
      ::DDS::InstanceHandle_t handle
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:210
  
  virtual ::CORBA::Boolean _is_a (
      const char *type_id
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  virtual const char* _interface_repository_id (void) const;
  virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
private:
  TAO::Collocation_Proxy_Broker *the_TAO_PubMessageDataWriter_Proxy_Broker_;

protected:
  // Concrete interface only.
  PubMessageDataWriter (void);
  
  // These methods travese the inheritance tree and set the
  // parents piece of the given class in the right mode.
  virtual void PubMessageDataWriter_setup_collocation (void);
  
  // Concrete non-local interface only.
  PubMessageDataWriter (
      IOP::IOR *ior,
      TAO_ORB_Core *orb_core = 0
    );
  
  // Non-local interface only.
  PubMessageDataWriter (
      TAO_Stub *objref,
      ::CORBA::Boolean _tao_collocated = 0,
      TAO_Abstract_ServantBase *servant = 0,
      TAO_ORB_Core *orb_core = 0
    );
  
  virtual ~PubMessageDataWriter (void);

private:
  // Private and unimplemented for concrete interfaces.
  PubMessageDataWriter (const PubMessageDataWriter &);
  
  void operator= (const PubMessageDataWriter &);
};

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_interface.cpp:646

#if !defined (_PUBMESSAGEDATAREADER__VAR_OUT_CH_)
#define _PUBMESSAGEDATAREADER__VAR_OUT_CH_

class PubMessageDataReader;
typedef PubMessageDataReader *PubMessageDataReader_ptr;

typedef
  TAO_Objref_Var_T<
      PubMessageDataReader
    >
  PubMessageDataReader_var;

typedef
  TAO_Objref_Out_T<
      PubMessageDataReader
    >
  PubMessageDataReader_out;

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ch.cpp:54

#if !defined (_PUBMESSAGEDATAREADER_CH_)
#define _PUBMESSAGEDATAREADER_CH_

class  PubMessageDataReader
  : public virtual ::TAO::DCPS::DataReaderRemote
{
public:
  friend class TAO::Narrow_Utils<PubMessageDataReader>;
  typedef PubMessageDataReader_ptr _ptr_type;
  typedef PubMessageDataReader_var _var_type;
  
  // The static operations.
  static PubMessageDataReader_ptr _duplicate (PubMessageDataReader_ptr obj);
  
  static void _tao_release (PubMessageDataReader_ptr obj);
  
  static PubMessageDataReader_ptr _narrow (
      ::CORBA::Object_ptr obj
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  static PubMessageDataReader_ptr _unchecked_narrow (
      ::CORBA::Object_ptr obj
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  static PubMessageDataReader_ptr _nil (void)
  {
    return static_cast<PubMessageDataReader_ptr> (0);
  }
  
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t read (
      ::PubMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t take (
      ::PubMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDSPerfTest::PubMessage & received_data,
      ::DDS::SampleInfo & sample_info
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDSPerfTest::PubMessage & received_data,
      ::DDS::SampleInfo & sample_info
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t read_instance (
      ::PubMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t take_instance (
      ::PubMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t read_next_instance (
      ::PubMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t take_next_instance (
      ::PubMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t return_loan (
      ::PubMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSPerfTest::PubMessage & key_holder,
      ::DDS::InstanceHandle_t handle
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    )
    ACE_THROW_SPEC ((
      ::CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:210
  
  virtual ::CORBA::Boolean _is_a (
      const char *type_id
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  virtual const char* _interface_repository_id (void) const;
  virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
private:
  TAO::Collocation_Proxy_Broker *the_TAO_PubMessageDataReader_Proxy_Broker_;

protected:
  // Concrete interface only.
  PubMessageDataReader (void);
  
  // These methods travese the inheritance tree and set the
  // parents piece of the given class in the right mode.
  virtual void PubMessageDataReader_setup_collocation (void);
  
  // Concrete non-local interface only.
  PubMessageDataReader (
      IOP::IOR *ior,
      TAO_ORB_Core *orb_core = 0
    );
  
  // Non-local interface only.
  PubMessageDataReader (
      TAO_Stub *objref,
      ::CORBA::Boolean _tao_collocated = 0,
      TAO_Abstract_ServantBase *servant = 0,
      TAO_ORB_Core *orb_core = 0
    );
  
  virtual ~PubMessageDataReader (void);

private:
  // Private and unimplemented for concrete interfaces.
  PubMessageDataReader (const PubMessageDataReader &);
  
  void operator= (const PubMessageDataReader &);
};

#endif /* end #if !defined */

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// be/be_visitor_root/root.cpp:139

extern 
TAO::Collocation_Proxy_Broker *
(*_TAO_PubMessageTypeSupport_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

extern 
TAO::Collocation_Proxy_Broker *
(*_TAO_PubMessageDataWriter_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

extern 
TAO::Collocation_Proxy_Broker *
(*_TAO_PubMessageDataReader_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:61

// Traits specializations.
namespace TAO
{

#if !defined (_PUBMESSAGETYPESUPPORT__TRAITS_)
#define _PUBMESSAGETYPESUPPORT__TRAITS_
  
  template<>
  struct  Objref_Traits< ::PubMessageTypeSupport>
  {
    static ::PubMessageTypeSupport_ptr duplicate (
        ::PubMessageTypeSupport_ptr
      );
    static void release (
        ::PubMessageTypeSupport_ptr
      );
    static ::PubMessageTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        ::PubMessageTypeSupport_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */

#if !defined (_PUBMESSAGEDATAWRITER__TRAITS_)
#define _PUBMESSAGEDATAWRITER__TRAITS_
  
  template<>
  struct  Objref_Traits< ::PubMessageDataWriter>
  {
    static ::PubMessageDataWriter_ptr duplicate (
        ::PubMessageDataWriter_ptr
      );
    static void release (
        ::PubMessageDataWriter_ptr
      );
    static ::PubMessageDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        ::PubMessageDataWriter_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */

#if !defined (_PUBMESSAGEDATAREADER__TRAITS_)
#define _PUBMESSAGEDATAREADER__TRAITS_
  
  template<>
  struct  Objref_Traits< ::PubMessageDataReader>
  {
    static ::PubMessageDataReader_ptr duplicate (
        ::PubMessageDataReader_ptr
      );
    static void release (
        ::PubMessageDataReader_ptr
      );
    static ::PubMessageDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        ::PubMessageDataReader_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_PubMessageSeq_H_
#define _TAO_CDR_OP_PubMessageSeq_H_

 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &,
    const PubMessageSeq &
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &,
    PubMessageSeq &
  );

#endif /* _TAO_CDR_OP_PubMessageSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const PubMessageTypeSupport_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, PubMessageTypeSupport_ptr &);

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const PubMessageDataWriter_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, PubMessageDataWriter_ptr &);

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const PubMessageDataReader_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, PubMessageDataReader_ptr &);

// TAO_IDL - Generated from
// be/be_visitor_sequence/serializer_op_ch.cpp:71

#if !defined _TAO_SERIALIZER_OP_PubMessageSeq_H_
#define _TAO_SERIALIZER_OP_PubMessageSeq_H_

 ::CORBA::Boolean _tao_is_bounded_size (
    const PubMessageSeq &
  );
 size_t _dcps_max_marshaled_size (
    const PubMessageSeq &
  );
 size_t _dcps_find_size (
    const PubMessageSeq &
  );


 ::CORBA::Boolean operator<< (
    TAO::DCPS::Serializer &,
    const PubMessageSeq &
  );
 ::CORBA::Boolean operator>> (
    TAO::DCPS::Serializer &,
    PubMessageSeq &
  );

#endif /* _TAO_SERIALIZER_OP_PubMessageSeq_H_ */

// TAO_IDL - Generated from
// be/be_codegen.cpp:1101

TAO_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "PubMessageTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */


