#ifndef THROUGHPUTTEST_IDL
#define THROUGHPUTTEST_IDL

module TP_Test
{
  typedef sequence<octet, 4> Bytes4Seq;
  typedef sequence<octet, 8> Bytes8Seq;
  typedef sequence<octet, 16> Bytes16Seq;
  typedef sequence<octet, 32> Bytes32Seq;
  typedef sequence<octet, 64> Bytes64Seq;
  typedef sequence<octet, 128> Bytes128Seq;
  typedef sequence<octet, 256> Bytes256Seq;
  typedef sequence<octet, 512> Bytes512Seq;
  typedef sequence<octet, 1024> Bytes1024Seq;
  typedef sequence<octet, 2048> Bytes2048Seq;
  typedef sequence<octet, 4096> Bytes4096Seq;
  typedef sequence<octet, 8192> Bytes8192Seq;
  typedef sequence<octet, 16384> Bytes16384Seq;
  
  struct Bytes4
  {
    Bytes4Seq data;
  };
  
  struct Bytes8
  {
    Bytes8Seq data;
  };
  
  struct Bytes16
  {
    Bytes16Seq data;
  };
  
  struct Bytes32
  {
    Bytes32Seq data;
  };
  
  struct Bytes64
  {
    Bytes64Seq data;
  };
  
  struct Bytes128
  {
    Bytes128Seq data;
  };
  
  struct Bytes256
  {
    Bytes256Seq data;
  };
  
  struct Bytes512
  {
    Bytes512Seq data;
  };
  
  struct Bytes1024
  {
    Bytes1024Seq data;
  };
  
  struct Bytes2048
  {
    Bytes2048Seq data;
  };
  
  struct Bytes4096
  {
    Bytes4096Seq data;
  };
  
  struct Bytes8192
  {
    Bytes8192Seq data;
  };
  
  struct Bytes16384
  {
    Bytes16384Seq data;
  };
    
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes4"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes8"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes16"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes32"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes64"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes128"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes256"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes512"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes1024"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes2048"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes4096"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes8192"
  #pragma DCPS_DATA_TYPE "TP_Test::Bytes16384"
  
  struct Nested
  {
    string info;
    long index;
  };
  
  typedef sequence<Nested> NestedSeq;
  
  struct Outer
  {
    long length;
    NestedSeq nested_member;
  };
  
  typedef sequence<Outer, 4> Complex4Seq;
  typedef sequence<Outer, 8> Complex8Seq;
  typedef sequence<Outer, 16> Complex16Seq;
  typedef sequence<Outer, 32> Complex32Seq;
  typedef sequence<Outer, 64> Complex64Seq;
  typedef sequence<Outer, 128> Complex128Seq;
  typedef sequence<Outer, 256> Complex256Seq;
  typedef sequence<Outer, 512> Complex512Seq;
  typedef sequence<Outer, 1024> Complex1024Seq;
  typedef sequence<Outer, 2048> Complex2048Seq;
  typedef sequence<Outer, 4096> Complex4096Seq;
  typedef sequence<Outer, 8192> Complex8192Seq;
  typedef sequence<Outer, 16384> Complex16384Seq;
  
  struct Complex4
  {
    Complex4Seq data;
  };
  
  struct Complex8
  {
    Complex8Seq data;
  };
  
  struct Complex16
  {
    Complex16Seq data;
  };
  
  struct Complex32
  {
    Complex32Seq data;
  };
  
  struct Complex64
  {
    Complex64Seq data;
  };
  
  struct Complex128
  {
    Complex128Seq data;
  };
  
  struct Complex256
  {
    Complex256Seq data;
  };
  
  struct Complex512
  {
    Complex512Seq data;
  };
  
  struct Complex1024
  {
    Complex1024Seq data;
  };
  
  struct Complex2048
  {
    Complex2048Seq data;
  };
  
  struct Complex4096
  {
    Complex4096Seq data;
  };
  
  struct Complex8192
  {
    Complex8192Seq data;
  };
  
  struct Complex16384
  {
    Complex16384Seq data;
  };
    
  #pragma DCPS_DATA_TYPE "TP_Test::Complex4"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex8"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex16"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex32"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex64"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex128"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex256"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex512"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex1024"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex2048"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex4096"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex8192"
  #pragma DCPS_DATA_TYPE "TP_Test::Complex16384"
};

#endif /* THROUGHPUTTEST_IDL */

