// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html


// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_QuitMsgSeq_I_
#define _TAO_CDR_OP_TP_Test_QuitMsgSeq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::QuitMsgSeq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::QuitMsgSeq &
  );

#endif /* _TAO_CDR_OP_TP_Test_QuitMsgSeq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes4Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes4Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes4Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes4Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes4Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes8Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes8Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes8Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes8Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes8Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes16Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes16Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes16Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes16Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes16Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes32Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes32Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes32Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes32Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes32Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes64Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes64Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes64Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes64Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes64Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes128Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes128Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes128Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes128Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes128Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes256Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes256Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes256Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes256Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes256Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes512Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes512Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes512Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes512Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes512Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes1024Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes1024Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes1024Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes1024Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes1024Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes2048Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes2048Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes2048Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes2048Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes2048Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes4096Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes4096Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes4096Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes4096Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes4096Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes8192Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes8192Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes8192Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes8192Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes8192Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Bytes16384Seq_I_
#define _TAO_CDR_OP_TP_Test_Bytes16384Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Bytes16384Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Bytes16384Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Bytes16384Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex4Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex4Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex4Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex4Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex4Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex8Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex8Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex8Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex8Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex8Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex16Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex16Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex16Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex16Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex16Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex32Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex32Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex32Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex32Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex32Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex64Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex64Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex64Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex64Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex64Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex128Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex128Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex128Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex128Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex128Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex256Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex256Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex256Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex256Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex256Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex512Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex512Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex512Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex512Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex512Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex1024Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex1024Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex1024Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex1024Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex1024Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex2048Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex2048Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex2048Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex2048Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex2048Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex4096Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex4096Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex4096Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex4096Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex4096Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex8192Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex8192Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex8192Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex8192Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex8192Seq_I_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ci.cpp:81

#if !defined _TAO_CDR_OP_TP_Test_Complex16384Seq_I_
#define _TAO_CDR_OP_TP_Test_Complex16384Seq_I_

CORBA::Boolean  operator<< (
    TAO_OutputCDR &,
    const TP_Test::Complex16384Seq &
  );

CORBA::Boolean  operator>> (
    TAO_InputCDR &,
    TP_Test::Complex16384Seq &
  );

#endif /* _TAO_CDR_OP_TP_Test_Complex16384Seq_I_ */

