#!/bin/bash

nddsgen -language C++ -d . -optimization 2 -replace NDDSLatencyPacket.idl


nddsgen -language C++ -d . -replace -makefile i86Linux2.6gcc3.4.3 NDDSLatencyPacket.idl


make -f makefile_NDDSLatencyPacket_i86Linux2.6gcc3.4.3


