#!/bin/bash

nddsgen -language C++ -d . -optimization 2 -replace latency.idl


nddsgen -language C++ -d . -replace -makefile i86Linux2.6gcc3.4.3 latency.idl


#make -f makefile_latency_i86Linux2.6gcc3.4.3


