/*
 (c) Copyright, Real-Time Innovations, 2005.  All rights reserved.
 No duplications, whole or partial, manual or electronic, may be made
 without express written permission.  Any such copies, or
 revisions thereof, must display this notice unaltered.
 This code contains trade secrets of Real-Time Innovations, Inc.
*/

/* If you want to test the shared memory transport plugin's capability to
   send messages larger than UDP packet size limit of 64K, increase this
   value.  Please note that doing so will turn off the built-in UDPv4 plugin.
*/
const short MAX_MSG_LENGTH = 16384;// 131072

struct PubMessage {
    long seqnum;
    sequence<octet, MAX_MSG_LENGTH> data;
};

struct Nested
{
  long n_seqnum;
  string<20> n_data;
};

struct Outer
{
  long o_seqnum;
  sequence<Nested, 10> o_data;
};

struct PubMessage_Nest
{
  long seqnum;
  sequence<Outer, MAX_MSG_LENGTH> data;
};

struct AckMessage {
    long seqnum;
};
