#!/bin/bash


RESULT_FILE=./results_opensplice

if [[ -e "$RESULT_FILE" ]]
then 
  echo "Remove the current results..."
  rm $RESULT_FILE  
fi


# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

size=$1
count=$2

echo "\n\nsize: 4"
~/DDS/scripts/ospl_start

exec/start_sub -s 4 &

sleep 3

exec/start_pub -c 2000 -s 4 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE

sleep 3

echo "\n\nsize: 8"

#~/DDS/scripts/ospl_start

exec/start_sub -s 8 &

sleep 3

exec/start_pub -c 2000 -s 8 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE

sleep 3

echo "\n\nsize: 16"

#~/DDS/scripts/ospl_start

exec/start_sub -s 16 &

sleep 3

exec/start_pub -c 2000 -s 16 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE


sleep 3

echo "\n\nsize: 32"

#~/DDS/scripts/ospl_start

exec/start_sub -s 32 &

sleep 3

exec/start_pub -c 2000 -s 32 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE


sleep 3

echo "\n\nsize: 64"

#~/DDS/scripts/ospl_start

exec/start_sub -s 64 &

sleep 3

exec/start_pub -c 2000 -s 64 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE

sleep 3

echo "\n\nsize: 128"

#~/DDS/scripts/ospl_start

exec/start_sub -s 128 &

sleep 3

exec/start_pub -c 2000 -s 128 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE

sleep 3

echo "\n\nsize: 256"

#~/DDS/scripts/ospl_start

exec/start_sub -s 256 &

sleep 3

exec/start_pub -c 2000 -s 256 -d 1

#~/DDS/scripts/ospl_stop


cat ./results >> $RESULT_FILE

sleep 3

echo "\n\nsize: 512"

#~/DDS/scripts/ospl_start

exec/start_sub -s 512 &

sleep 3

exec/start_pub -c 2000 -s 512 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE

sleep 3

echo "\n\nsize: 1024"

#~/DDS/scripts/ospl_start

exec/start_sub -s 1024 &

sleep 3

exec/start_pub -c 2000 -s 1024 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE


sleep 3

echo "\n\nsize: 2048"

#~/DDS/scripts/ospl_start

exec/start_sub -s 2048 &

sleep 3

exec/start_pub -c 2000 -s 2048 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE

sleep 3

echo "\n\nsize: 4096"

#~/DDS/scripts/ospl_start

exec/start_sub -s 4096 &

sleep 3

exec/start_pub -c 1500 -s 4096 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE

sleep 3

echo "\n\nsize: 8192"

#~/DDS/scripts/ospl_start

exec/start_sub -s 8192 &

sleep 3

exec/start_pub -c 800 -s 8192 -d 1

#~/DDS/scripts/ospl_stop

cat ./results >> $RESULT_FILE


sleep 3

echo "\n\nsize: 16384"

#~/DDS/scripts/ospl_start

exec/start_sub -s 16384 &

sleep 3

exec/start_pub -c 500 -s 16384 -d 1

~/DDS/scripts/ospl_stop


cat ./results >> $RESULT_FILE









