#!/bin/bash


RESULT_FILE=./results_opensplice

if [[ -e "$RESULT_FILE" ]]
then 
  echo "Remove the current results..."
  rm $RESULT_FILE  
fi


# .bash_profile

size=$1
count=$2

sleep 3

echo "\n\nsize: 32768"

source ~/DDS/settings/ospl_environment

~/DDS/scripts/ospl_start

exec/start_sub -d 32768 &

sleep 3

exec/start_pub -r mine.txt -s 500 -d 32768

~/DDS/scripts/ospl_stop
