/* soapClient.cpp
   Generated by gSOAP 2.7.6c from Test.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.7.6c 2005-12-02 00:15:37 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__latencyByteArray(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct gSOAP_byte_array in, unsigned long &seq_num)
{	struct ns__latencyByteArray soap_tmp_ns__latencyByteArray;
	struct ns__latencyByteArrayResponse *soap_tmp_ns__latencyByteArrayResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = NULL;
	soap_tmp_ns__latencyByteArray.in = in;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__latencyByteArray(soap, &soap_tmp_ns__latencyByteArray);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__latencyByteArray(soap, &soap_tmp_ns__latencyByteArray, "ns:latencyByteArray", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__latencyByteArray(soap, &soap_tmp_ns__latencyByteArray, "ns:latencyByteArray", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_unsignedLong(soap, &seq_num);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__latencyByteArrayResponse = soap_get_ns__latencyByteArrayResponse(soap, NULL, "ns:latencyByteArrayResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	seq_num = soap_tmp_ns__latencyByteArrayResponse->seq_num;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__latencyNestedArray(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct gSOAP_outer_array in, unsigned long &seq_num)
{	struct ns__latencyNestedArray soap_tmp_ns__latencyNestedArray;
	struct ns__latencyNestedArrayResponse *soap_tmp_ns__latencyNestedArrayResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080";
	soap->encodingStyle = NULL;
	soap_tmp_ns__latencyNestedArray.in = in;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__latencyNestedArray(soap, &soap_tmp_ns__latencyNestedArray);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__latencyNestedArray(soap, &soap_tmp_ns__latencyNestedArray, "ns:latencyNestedArray", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__latencyNestedArray(soap, &soap_tmp_ns__latencyNestedArray, "ns:latencyNestedArray", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_unsignedLong(soap, &seq_num);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__latencyNestedArrayResponse = soap_get_ns__latencyNestedArrayResponse(soap, NULL, "ns:latencyNestedArrayResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	seq_num = soap_tmp_ns__latencyNestedArrayResponse->seq_num;
	return soap_closesock(soap);
}

/* End of soapClient.cpp */
