const long MAX_MSGLENGTH = 32768;

struct simpleType {
    long id;
    long payload;
};


#pragma keylist simpleType
#pragma DCPS_DATA_TYPE "simpleType"


struct innerStruct {
    long value;
};

struct nestedType {
    long id;
    innerStruct payload;
};


#pragma keylist nestedType
#pragma DCPS_DATA_TYPE "nestedType"


struct arrayType {
    long id;
    long payload[10];
};

#pragma keylist arrayType
#pragma DCPS_DATA_TYPE "arrayType"


struct stringType {
    long id;
    string payload;
};

#pragma keylist stringType
#pragma DCPS_DATA_TYPE "stringType"


typedef sequence<octet,MAX_MSG_LENGTH> OctetSequence;

struct sequenceType {
    OctetSequence payload;
};

#pragma keylist sequenceType
#pragma DCPS_DATA_TYPE "sequenceType"
