#ifndef OSPL_THROUGHPUTTEST_IDL
#define OSPL_THROUGHPUTTEST_IDL

module TP_Test
{
  typedef sequence<octet> BytesSequence;
  
  struct Bytes
  {
    unsigned long timestamp;
    BytesSequence data;
  };
  
#  pragma keylist Bytes
  
  struct Nested
  {
    string info;
    long index;
  };
  
  typedef sequence<Nested> NestedSequence;
  
  struct Outer
  {
    long length;
    NestedSequence nested_member;
  };
  
  typedef sequence<Outer> ComplexSequence;
  
  struct Complex
  {
    unsigned long timestamp;
    ComplexSequence data;
  };
  
#  pragma keylist Complex
};

#endif /* OSPL_THROUGHPUTTEST_IDL */

