const short MAX_MSG_LENGTH=16384;

//  typedef sequence<octet, MAX_LENGTH> Bytes4Seq;
//  typedef sequence<octet, 8> Bytes8Seq;
//  typedef sequence<octet, 16> Bytes16Seq;
//  typedef sequence<octet, 32> Bytes32Seq;
//  typedef sequence<octet, 64> Bytes64Seq;
//  typedef sequence<octet, 128> Bytes128Seq;
//  typedef sequence<octet, 256> Bytes256Seq;
//  typedef sequence<octet, 512> Bytes512Seq;
//  typedef sequence<octet, 1024> Bytes1024Seq;
//  typedef sequence<octet, 2048> Bytes2048Seq;
//  typedef sequence<octet, 4096> Bytes4096Seq;
//  typedef sequence<octet, 8192> Bytes8192Seq;
//  typedef sequence<octet, 16384> Bytes16384Seq;

  
  struct Bytes4
  {
    sequence<octet, MAX_MSG_LENGTH> data;
  };
  
  struct Bytes8
  {
    sequence<octet, 8> data;
  };
  
  struct Bytes16
  {
    sequence<octet, 16> data;
  };
  
  struct Bytes32
  {
    sequence<octet, 32> data;
  };
  
  struct Bytes64
  {
    sequence<octet, 64> data;
  };
  
  struct Bytes128
  {
    sequence<octet, 128> data;
  };
  
  struct Bytes256
  {
    sequence<octet, 256> data;
  };
  
  struct Bytes512
  {
    sequence<octet, 512> data;
  };
  
  struct Bytes1024
  {
    sequence<octet, 1024> data;
  };
  
  struct Bytes2048
  {
    sequence<octet, 2048> data;
  };
  
  struct Bytes4096
  {
    sequence<octet, 4096> data;
  };
  
  struct Bytes8192
  {
    sequence<octet, 8192> data;
  };
  
  struct Bytes16384
  {
    sequence<octet, 16384> data;
  };
    
  struct Nested
  {
    string info;
    long index;
  };
  
//  typedef sequence<Nested> NestedSeq;
  
  struct Outer
  {
    long length;
    sequence<Nested, 10> nested_member;
  };
  
//  typedef sequence<Outer, 4> Complex4Seq;
//  typedef sequence<Outer, 8> Complex8Seq;
//  typedef sequence<Outer, 16> Complex16Seq;
//  typedef sequence<Outer, 32> Complex32Seq;
//  typedef sequence<Outer, 64> Complex64Seq;
//  typedef sequence<Outer, 128> Complex128Seq;
//  typedef sequence<Outer, 256> Complex256Seq;
//  typedef sequence<Outer, 512> Complex512Seq;
//  typedef sequence<Outer, 1024> Complex1024Seq;
//  typedef sequence<Outer, 2048> Complex2048Seq;
//  typedef sequence<Outer, 4096> Complex4096Seq;
//  typedef sequence<Outer, 8192> Complex8192Seq;
//  typedef sequence<Outer, 16384> Complex16384Seq;
  
  struct Complex4
  {
    sequence<Outer, 4> data;
  };
  
  struct Complex8
  {
    sequence<Outer, 8> data;
  };
  
  struct Complex16
  {
    sequence<Outer, 16> data;
  };
  
  struct Complex32
  {
    sequence<Outer, 32> data;
  };
  
  struct Complex64
  {
    sequence<Outer, 64> data;
  };
  
  struct Complex128
  {
    sequence<Outer, 128> data;
  };
  
  struct Complex256
  {
    sequence<Outer, 256> data;
  };
  
  struct Complex512
  {
    sequence<Outer, 512> data;
  };
  
  struct Complex1024
  {
    sequence<Outer, 1024> data;
  };
  
  struct Complex2048
  {
    sequence<Outer, 2048> data;
  };
  
  struct Complex4096
  {
    sequence<Outer, 4096> data;
  };
  
  struct Complex8192
  {
    sequence<Outer, 8192> data;
  };
  
  struct Complex16384
  {
    sequence<Outer, 16384> data;
  };

