/* soapServer.cpp
   Generated by gSOAP 2.7.6c from Test.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.7.6c 2005-11-29 20:30:54 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (!--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:conversionByteArray"))
		return soap_serve_ns__conversionByteArray(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:conversionNestedArray"))
		return soap_serve_ns__conversionNestedArray(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__conversionByteArray(struct soap *soap)
{	struct ns__conversionByteArray soap_tmp_ns__conversionByteArray;
	struct ns__conversionByteArrayResponse soap_tmp_ns__conversionByteArrayResponse;
	soap_default_ns__conversionByteArrayResponse(soap, &soap_tmp_ns__conversionByteArrayResponse);
	soap_default_ns__conversionByteArray(soap, &soap_tmp_ns__conversionByteArray);
	soap->encodingStyle = NULL;
	if (!soap_get_ns__conversionByteArray(soap, &soap_tmp_ns__conversionByteArray, "ns:conversionByteArray", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__conversionByteArray(soap, soap_tmp_ns__conversionByteArray.in, soap_tmp_ns__conversionByteArrayResponse.seq_num);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__conversionByteArrayResponse(soap, &soap_tmp_ns__conversionByteArrayResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__conversionByteArrayResponse(soap, &soap_tmp_ns__conversionByteArrayResponse, "ns:conversionByteArrayResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__conversionByteArrayResponse(soap, &soap_tmp_ns__conversionByteArrayResponse, "ns:conversionByteArrayResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__conversionNestedArray(struct soap *soap)
{	struct ns__conversionNestedArray soap_tmp_ns__conversionNestedArray;
	struct ns__conversionNestedArrayResponse soap_tmp_ns__conversionNestedArrayResponse;
	soap_default_ns__conversionNestedArrayResponse(soap, &soap_tmp_ns__conversionNestedArrayResponse);
	soap_default_ns__conversionNestedArray(soap, &soap_tmp_ns__conversionNestedArray);
	soap->encodingStyle = NULL;
	if (!soap_get_ns__conversionNestedArray(soap, &soap_tmp_ns__conversionNestedArray, "ns:conversionNestedArray", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__conversionNestedArray(soap, soap_tmp_ns__conversionNestedArray.in, soap_tmp_ns__conversionNestedArrayResponse.seq_num);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__conversionNestedArrayResponse(soap, &soap_tmp_ns__conversionNestedArrayResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__conversionNestedArrayResponse(soap, &soap_tmp_ns__conversionNestedArrayResponse, "ns:conversionNestedArrayResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__conversionNestedArrayResponse(soap, &soap_tmp_ns__conversionNestedArrayResponse, "ns:conversionNestedArrayResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

/* End of soapServer.cpp */
