/*
 (c) Copyright, Real-Time Innovations, 2005.  All rights reserved.
 No duplications, whole or partial, manual or electronic, may be made
 without express written permission.  Any such copies, or
 revisions thereof, must display this notice unaltered.
 This code contains trade secrets of Real-Time Innovations, Inc.
*/

// (JP) If we change the name of this IDL file, we can remove
// the copyright block above. The hope is to use the same IDL
// file for all implementations, but that may not yet be
// possible (see below).

// (JP) It's preferred practice in IDL to typedef a sequence or
// an array outside the scope where it's to be used as a
// member. Using it directly isn't forbidden (yet) but
// deprecated. NDDS handles this ok, but I think one of the
// others may have a problem with it. We'll soon discover
// if it's true, then we can report it to the vendor, and
// change the IDL if we have to. In any case, we'll have to
// declare an empty keylist for OpenSplice.
typedef sequence<octet> OctetSeq;

struct BytesData
{
  unsigned long timestamp;
  OctetSeq data;
};
  
