struct simpleType {
  long id;
  long payload;
};

struct innerStruct {
  long value;
};
struct nestedType {
  long id;
  innerStruct payload;
};

struct arrayType {
  long id;
  long payload[10];
};

struct stringType {
  long id;
  string payload;
};

