// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:164

#ifndef _TAO_IDL_PUBMESSAGEC_H_
#define _TAO_IDL_PUBMESSAGEC_H_

#include /**/ "ace/pre.h"


#include "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/Environment.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Versioned_Namespace.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace pubdata
{
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:258
  
  struct pubmessage;
  
  typedef
    TAO_Var_Var_T<
        pubmessage
      >
    pubmessage_var;
  
  typedef
    TAO_Out_T<
        pubmessage,
        pubmessage_var
      >
    pubmessage_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  pubmessage
  {
    typedef pubmessage_var _var_type;
    
    static void _tao_any_destructor (void *);
    ::CORBA::Long seqnum;
    
    
    // TAO_IDL - Generated from
    // be/be_visitor_sequence/sequence_ch.cpp:101

#if !defined (_PUBDATA_PUBMESSAGE__TAO_SEQ_CORBA_OCTET__CH_)
#define _PUBDATA_PUBMESSAGE__TAO_SEQ_CORBA_OCTET__CH_
    
    class  _tao_seq_CORBA_Octet_
      : public
          TAO_Unbounded_Sequence<
              CORBA::Octet
            >
    {
    public:
      _tao_seq_CORBA_Octet_ (void);
      _tao_seq_CORBA_Octet_ ( ::CORBA::ULong max);
      _tao_seq_CORBA_Octet_ (
          ::CORBA::ULong max,
          ::CORBA::ULong length,
          ::CORBA::Octet* buffer, 
          ::CORBA::Boolean release = 0
        );
      _tao_seq_CORBA_Octet_ (const _tao_seq_CORBA_Octet_ &);
      ~_tao_seq_CORBA_Octet_ (void);

#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
      _tao_seq_CORBA_Octet_ (
          ::CORBA::ULong length,
          const ACE_Message_Block* mb
        )
        : TAO_Unbounded_Sequence< ::CORBA::Octet> (length, mb) {}
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
    };

#endif /* end #if !defined */
    
    // TAO_IDL - Generated from
    // be/be_visitor_field/field_ch.cpp:393
    
    typedef _tao_seq_CORBA_Octet_ _data_seq;
    _tao_seq_CORBA_Octet_ data;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_pubmessage;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module pubdata

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:61

// Traits specializations.
namespace TAO
{
}

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:53

 void operator<<= (::CORBA::Any &, const pubdata::pubmessage &); // copying version
 void operator<<= (::CORBA::Any &, pubdata::pubmessage*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, pubdata::pubmessage *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const pubdata::pubmessage *&);

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const pubdata::pubmessage &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, pubdata::pubmessage &);

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_pubdata_pubmessage__tao_seq_CORBA_Octet__H_
#define _TAO_CDR_OP_pubdata_pubmessage__tao_seq_CORBA_Octet__H_

 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &,
    const pubdata::pubmessage::_tao_seq_CORBA_Octet_ &
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &,
    pubdata::pubmessage::_tao_seq_CORBA_Octet_ &
  );

#endif /* _TAO_CDR_OP_pubdata_pubmessage__tao_seq_CORBA_Octet__H_ */

// TAO_IDL - Generated from
// be/be_codegen.cpp:1101

TAO_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "pubmessageC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */


